[workspace]
resolver = "2"
members = ["crates/jedem", "crates/jedem-macros", "demo/hello", "demo/hello-py"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/PowderworksCode/jedem"

[workspace.dependencies]
jedem = { path = "crates/jedem", version = "0.1.0" }
jedem-macros = { path = "crates/jedem-macros", version = "0.1.0" }
