// @generated by jedem for the `node` target. Do not edit.
// Surface `hello` v0.1.0. Regenerate with `cargo jedem generate`.

fn main() {
    // Leave Node's symbols unresolved; the host supplies them at load.
    napi_build::setup();
}
