//! GENERATED by jedem for the `python` target. Do not edit.
//!
//! Surface `hello` v0.1.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.

#![allow(clippy::all)]
#![allow(unused_imports)]

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

/// A core error surfaces as a Python exception carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> PyErr {
    PyValueError::new_err(e.to_string())
}

// ---- Hello ----

/// Greet someone by name.
#[pyfunction]
pub fn greet(name: &str) -> String {
    hello::Hello::greet(name)
}

/// Greet someone, refusing an empty name.
///
/// Fallible: the `Result` becomes a raised exception in Python, not an
/// error value the caller has to remember to check.
#[pyfunction]
pub fn greet_checked(name: &str) -> PyResult<String> {
    hello::Hello::greet_checked(name).map_err(err)
}

/// Add two integers. Infallible, so there is no error seam at all.
#[pyfunction]
pub fn add(a: i64, b: i64) -> i64 {
    hello::Hello::add(a, b)
}

/// Repeat some text, or nothing at all when `times` is not positive.
#[pyfunction]
pub fn repeat(text: &str, times: i32) -> Option<String> {
    hello::Hello::repeat(text, times)
}

/// Split text on a separator.
#[pyfunction]
pub fn split(text: &str, sep: &str) -> Vec<String> {
    hello::Hello::split(text, sep)
}

/// Reverse a byte string: bytes in, bytes out.
#[pyfunction]
pub fn reverse_bytes(data: &[u8]) -> Vec<u8> {
    hello::Hello::reverse_bytes(data)
}

/// Exported under a pinned name, to prove the spelling is respected.
#[pyfunction]
#[pyo3(name = "shout")]
pub fn shout(text: &str) -> String {
    hello::Hello::shout_it(text)
}

/// Register everything on the module. Call this from your `#[pymodule]`.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(greet, m)?)?;
    m.add_function(wrap_pyfunction!(greet_checked, m)?)?;
    m.add_function(wrap_pyfunction!(add, m)?)?;
    m.add_function(wrap_pyfunction!(repeat, m)?)?;
    m.add_function(wrap_pyfunction!(split, m)?)?;
    m.add_function(wrap_pyfunction!(reverse_bytes, m)?)?;
    m.add_function(wrap_pyfunction!(shout, m)?)?;
    Ok(())
}
