//! @generated by jedem for the `node` target. Do not edit.
//!
//! Surface `hello` v0.1.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.
//!
//! Regenerate with `cargo jedem generate`.

#![allow(clippy::all)]
#![allow(unused_imports)]
// napi registers each function at module load, so nothing in this crate
// references them by name and rustc cannot tell they are used.
#![allow(dead_code)]

use napi_derive::napi;

/// A core error surfaces as a thrown JS `Error` carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

// ---- Hello ----

/// Greet someone by name.
#[napi(js_name = "greet")]
pub fn greet(name: String) -> String {
    hello::Hello::greet(&name)
}

/// Greet someone, refusing an empty name.
///
/// Fallible: the `Result` becomes whatever that language uses for failure
/// -- a raised exception, a thrown error -- not an error value the caller
/// has to remember to check. A doc comment is written once and read in
/// every binding, so it should not name one language.
#[napi(js_name = "greetChecked")]
pub fn greet_checked(name: String) -> napi::Result<String> {
    hello::Hello::greet_checked(&name).map_err(err)
}

/// Add two integers. Infallible, so there is no error seam at all.
#[napi(js_name = "add")]
pub fn add(a: i64, b: i64) -> i64 {
    hello::Hello::add(a, b)
}

/// Repeat some text, or nothing at all when `times` is not positive.
#[napi(js_name = "repeat")]
pub fn repeat(text: String, times: i32) -> Option<String> {
    hello::Hello::repeat(&text, times)
}

/// Split text on a separator.
#[napi(js_name = "split")]
pub fn split(text: String, sep: String) -> Vec<String> {
    hello::Hello::split(&text, &sep)
}

/// Reverse a byte string: bytes in, bytes out.
#[napi(js_name = "reverseBytes")]
pub fn reverse_bytes(data: napi::bindgen_prelude::Uint8Array) -> napi::bindgen_prelude::Buffer {
    hello::Hello::reverse_bytes(&data).into()
}

/// Exported under a pinned name, to prove the spelling is respected.
#[napi(js_name = "shout")]
pub fn shout_it(text: String) -> String {
    hello::Hello::shout_it(&text)
}

// ---- fallible ----

/// Parse a number, then halve it. Two different failure types, one
/// signature, no `map_err` in sight.
#[napi(js_name = "halveParsed")]
pub fn halve_parsed(text: String) -> napi::Result<i64> {
    hello::fallible::halve_parsed(&text).map_err(err)
}

/// A plain concrete error still works, unchanged.
#[napi(js_name = "checked")]
pub fn checked(text: String) -> napi::Result<String> {
    hello::fallible::checked(&text).map_err(err)
}
