//! @generated by jedem for the `python` target. Do not edit.
//!
//! Surface `hello` v0.1.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.
//!
//! Regenerate with `cargo jedem generate`.

#![allow(clippy::all)]
#![allow(unused_imports)]

use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;

/// A core error surfaces as a Python exception carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> PyErr {
    PyValueError::new_err(e.to_string())
}

/// A handle is empty only between a builder taking its value out and putting
/// it back, so seeing this means that builder panicked. The handle cannot be
/// repaired -- Rust consumed the value -- so every later call says so.
const EMPTIED: &str = "this handle was emptied by a builder that panicked";
/// How far along a value is — the shape jawohl's `Syntax` has, and the reason
/// enums exist: without them this crossed as a magic string.
#[pyclass(eq, eq_int)]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Ripeness {
    Missing,
    Partial,
    Done,
    #[pyo3(name = "not_applicable")]
    NotApplicable,
}

impl From<hello::Ripeness> for Ripeness {
    fn from(v: hello::Ripeness) -> Self {
        match v {
            hello::Ripeness::Missing => Self::Missing,
            hello::Ripeness::Partial => Self::Partial,
            hello::Ripeness::Done => Self::Done,
            hello::Ripeness::NotApplicable => Self::NotApplicable,
        }
    }
}

impl From<Ripeness> for hello::Ripeness {
    fn from(v: Ripeness) -> Self {
        match v {
            Ripeness::Missing => Self::Missing,
            Ripeness::Partial => Self::Partial,
            Ripeness::Done => Self::Done,
            Ripeness::NotApplicable => Self::NotApplicable,
        }
    }
}

// ---- Hello ----

/// Greet someone by name.
#[pyfunction]
pub fn greet(name: &str) -> String {
    hello::Hello::greet(name)
}

/// Greet someone, refusing an empty name.
///
/// Fallible: the `Result` becomes whatever that language uses for failure
/// -- a raised exception, a thrown error -- not an error value the caller
/// has to remember to check. A doc comment is written once and read in
/// every binding, so it should not name one language.
#[pyfunction]
pub fn greet_checked(name: &str) -> PyResult<String> {
    hello::Hello::greet_checked(name).map_err(err)
}

/// Add two integers. Infallible, so there is no error seam at all.
#[pyfunction]
pub fn add(a: i64, b: i64) -> i64 {
    hello::Hello::add(a, b)
}

/// Repeat some text, or nothing at all when `times` is not positive.
#[pyfunction]
pub fn repeat(text: &str, times: i32) -> Option<String> {
    hello::Hello::repeat(text, times)
}

/// Split text on a separator.
#[pyfunction]
pub fn split(text: &str, sep: &str) -> Vec<String> {
    hello::Hello::split(text, sep)
}

/// Reverse a byte string: bytes in, bytes out.
#[pyfunction]
pub fn reverse_bytes(data: &[u8]) -> Vec<u8> {
    hello::Hello::reverse_bytes(data)
}

/// Exported under a pinned name, to prove the spelling is respected.
#[pyfunction]
#[pyo3(name = "shout")]
pub fn shout(text: &str) -> String {
    hello::Hello::shout_it(text)
}

// ---- fallible ----

/// Parse a number, then halve it. Two different failure types, one
/// signature, no `map_err` in sight.
#[pyfunction]
pub fn halve_parsed(text: &str) -> PyResult<i64> {
    hello::fallible::halve_parsed(text).map_err(err)
}

/// A plain concrete error still works, unchanged.
#[pyfunction]
pub fn checked(text: &str) -> PyResult<String> {
    hello::fallible::checked(text).map_err(err)
}

// ---- ripeness ----

/// Classify a length. Returns an enum.
#[pyfunction]
pub fn classify(len: i32) -> Ripeness {
    hello::ripeness::classify(len).into()
}

/// Is it safe to act on? Takes an enum.
#[pyfunction]
pub fn is_settled(r: Ripeness) -> bool {
    hello::ripeness::is_settled(r.into())
}

/// An enum inside an Option.
#[pyfunction]
pub fn maybe(present: bool) -> Option<Ripeness> {
    hello::ripeness::maybe(present).map(|v| v.into())
}

// ---- Counter ----

#[pyclass]
pub struct Counter {
    inner: Option<hello::Counter>,
}

impl From<hello::Counter> for Counter {
    fn from(inner: hello::Counter) -> Self {
        Self { inner: Some(inner) }
    }
}

#[pymethods]
impl Counter {
    /// Start at zero.
    #[new]
    fn new() -> Self {
        hello::Counter::new().into()
    }

    /// Start at a given value, refusing a negative one.
    #[staticmethod]
    fn starting_at(start: i64) -> PyResult<Self> {
        Ok(hello::Counter::starting_at(start).map_err(err)?.into())
    }

    /// Start the tally somewhere other than zero.
    ///
    /// An ordinary Rust builder, unannotated and unchanged. It consumes `self`
    /// and returns `Self`, which names the same object -- so the bindings
    /// mutate in place and hand the same handle back, and the chain reads the
    /// same in every language.
    fn with_total(mut slf: PyRefMut<'_, Self>, total: i64) -> PyRefMut<'_, Self> {
        let inner = slf.inner.take().expect(EMPTIED);
        slf.inner = Some(inner.with_total(total));
        slf
    }

    /// Add to the tally. State persists across calls — that is the point.
    fn add(&mut self, n: i64) {
        self.get_mut().add(n);
    }

    /// The running total.
    fn total(&self) -> i64 {
        self.get().total()
    }

    /// How many times `add` has been called.
    fn steps(&self) -> i64 {
        self.get().steps()
    }

    /// A width that is not the boundary width.
    ///
    /// `usize` crosses as `i64`, because that is what Python and JavaScript
    /// have, and is cast back at the call site -- in both directions. Nothing
    /// about this signature had to change to say so.
    fn take_steps(&mut self, n: i64) -> i64 {
        (self.get_mut().take_steps(n as usize)) as i64
    }

    /// Halve the total, refusing an odd one.
    fn halve(&mut self) -> PyResult<i64> {
        self.get_mut().halve().map_err(err)
    }
}
impl Counter {
    fn get(&self) -> &hello::Counter {
        self.inner.as_ref().expect(EMPTIED)
    }
    fn get_mut(&mut self) -> &mut hello::Counter {
        self.inner.as_mut().expect(EMPTIED)
    }
}

/// Register everything on the module. Call this from your `#[pymodule]`.
pub fn register(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Ripeness>()?;
    m.add_class::<Counter>()?;
    m.add_function(wrap_pyfunction!(greet, m)?)?;
    m.add_function(wrap_pyfunction!(greet_checked, m)?)?;
    m.add_function(wrap_pyfunction!(add, m)?)?;
    m.add_function(wrap_pyfunction!(repeat, m)?)?;
    m.add_function(wrap_pyfunction!(split, m)?)?;
    m.add_function(wrap_pyfunction!(reverse_bytes, m)?)?;
    m.add_function(wrap_pyfunction!(shout, m)?)?;
    m.add_function(wrap_pyfunction!(halve_parsed, m)?)?;
    m.add_function(wrap_pyfunction!(checked, m)?)?;
    m.add_function(wrap_pyfunction!(classify, m)?)?;
    m.add_function(wrap_pyfunction!(is_settled, m)?)?;
    m.add_function(wrap_pyfunction!(maybe, m)?)?;
    Ok(())
}
