// @generated by jedem for the `python` target. Do not edit.
// Surface `hello` v0.1.0. Regenerate with `cargo jedem generate`.

mod generated;

#[pyo3::pymodule]
fn hello(m: &pyo3::Bound<'_, pyo3::types::PyModule>) -> pyo3::PyResult<()> {
    generated::register(m)
}
