//! @generated by jedem for the `node` target. Do not edit.
//!
//! Surface `hello` v0.1.0. Regenerate rather than editing: the source of truth
//! is the `#[jedem::export]` impl this was derived from.
//!
//! Regenerate with `cargo jedem generate`.

#![allow(clippy::all)]
#![allow(unused_imports)]
// napi registers each function at module load, so nothing in this crate
// references them by name and rustc cannot tell they are used.
#![allow(dead_code)]

use napi::bindgen_prelude::This;
use napi_derive::napi;

/// A core error surfaces as a thrown JS `Error` carrying its `Display` text --
/// the idiomatic seam, rather than an error value the caller has to remember
/// to inspect.
fn err(e: impl std::fmt::Display) -> napi::Error {
    napi::Error::from_reason(e.to_string())
}

/// A handle is empty only between a builder taking its value out and putting
/// it back, so seeing this means that builder panicked. The handle cannot be
/// repaired -- Rust consumed the value -- so every later call says so.
const EMPTIED: &str = "this handle was emptied by a builder that panicked";
/// How far along a value is — the shape jawohl's `Syntax` has, and the reason
/// enums exist: without them this crossed as a magic string.
#[napi(string_enum)]
pub enum Ripeness {
    Missing,
    Partial,
    Done,
    NotApplicable,
}

impl From<hello::Ripeness> for Ripeness {
    fn from(v: hello::Ripeness) -> Self {
        match v {
            hello::Ripeness::Missing => Self::Missing,
            hello::Ripeness::Partial => Self::Partial,
            hello::Ripeness::Done => Self::Done,
            hello::Ripeness::NotApplicable => Self::NotApplicable,
        }
    }
}

impl From<Ripeness> for hello::Ripeness {
    fn from(v: Ripeness) -> Self {
        match v {
            Ripeness::Missing => Self::Missing,
            Ripeness::Partial => Self::Partial,
            Ripeness::Done => Self::Done,
            Ripeness::NotApplicable => Self::NotApplicable,
        }
    }
}

// ---- Hello ----

/// Greet someone by name.
#[napi(js_name = "greet")]
pub fn greet(name: String) -> String {
    hello::Hello::greet(&name)
}

/// Greet someone, refusing an empty name.
///
/// Fallible: the `Result` becomes whatever that language uses for failure
/// -- a raised exception, a thrown error -- not an error value the caller
/// has to remember to check. A doc comment is written once and read in
/// every binding, so it should not name one language.
#[napi(js_name = "greetChecked")]
pub fn greet_checked(name: String) -> napi::Result<String> {
    hello::Hello::greet_checked(&name).map_err(err)
}

/// Add two integers. Infallible, so there is no error seam at all.
#[napi(js_name = "add")]
pub fn add(a: i64, b: i64) -> i64 {
    hello::Hello::add(a, b)
}

/// Repeat some text, or nothing at all when `times` is not positive.
#[napi(js_name = "repeat")]
pub fn repeat(text: String, times: i32) -> Option<String> {
    hello::Hello::repeat(&text, times)
}

/// Split text on a separator.
#[napi(js_name = "split")]
pub fn split(text: String, sep: String) -> Vec<String> {
    hello::Hello::split(&text, &sep)
}

/// Reverse a byte string: bytes in, bytes out.
#[napi(js_name = "reverseBytes")]
pub fn reverse_bytes(data: napi::bindgen_prelude::Uint8Array) -> napi::bindgen_prelude::Buffer {
    hello::Hello::reverse_bytes(&data).into()
}

/// Exported under a pinned name, to prove the spelling is respected.
#[napi(js_name = "shout")]
pub fn shout_it(text: String) -> String {
    hello::Hello::shout_it(&text)
}

// ---- fallible ----

/// Parse a number, then halve it. Two different failure types, one
/// signature, no `map_err` in sight.
#[napi(js_name = "halveParsed")]
pub fn halve_parsed(text: String) -> napi::Result<i64> {
    hello::fallible::halve_parsed(&text).map_err(err)
}

/// A plain concrete error still works, unchanged.
#[napi(js_name = "checked")]
pub fn checked(text: String) -> napi::Result<String> {
    hello::fallible::checked(&text).map_err(err)
}

// ---- ripeness ----

/// Classify a length. Returns an enum.
#[napi(js_name = "classify")]
pub fn classify(len: i32) -> Ripeness {
    hello::ripeness::classify(len).into()
}

/// Is it safe to act on? Takes an enum.
#[napi(js_name = "isSettled")]
pub fn is_settled(r: Ripeness) -> bool {
    hello::ripeness::is_settled(r.into())
}

/// An enum inside an Option.
#[napi(js_name = "maybe")]
pub fn maybe(present: bool) -> Option<Ripeness> {
    hello::ripeness::maybe(present).map(|v| v.into())
}

// ---- Counter ----

#[napi]
pub struct Counter {
    inner: Option<hello::Counter>,
}

impl From<hello::Counter> for Counter {
    fn from(inner: hello::Counter) -> Self {
        Self { inner: Some(inner) }
    }
}

#[napi]
impl Counter {
    /// Start at zero.
    #[napi(constructor)]
    pub fn new() -> Self {
        hello::Counter::new().into()
    }

    /// Start at a given value, refusing a negative one.
    #[napi(factory, js_name = "startingAt")]
    pub fn starting_at(start: i64) -> napi::Result<Self> {
        Ok(hello::Counter::starting_at(start).map_err(err)?.into())
    }

    /// Start the tally somewhere other than zero.
    ///
    /// An ordinary Rust builder, unannotated and unchanged. It consumes `self`
    /// and returns `Self`, which names the same object -- so the bindings
    /// mutate in place and hand the same handle back, and the chain reads the
    /// same in every language.
    #[napi(js_name = "withTotal")]
    pub fn with_total<'a>(&mut self, this: This<'a>, total: i64) -> This<'a> {
        let inner = self.inner.take().expect(EMPTIED);
        self.inner = Some(inner.with_total(total));
        this
    }

    /// Add to the tally. State persists across calls — that is the point.
    #[napi(js_name = "add")]
    pub fn add(&mut self, n: i64) {
        self.get_mut().add(n);
    }

    /// The running total.
    #[napi(js_name = "total")]
    pub fn total(&self) -> i64 {
        self.get().total()
    }

    /// How many times `add` has been called.
    #[napi(js_name = "steps")]
    pub fn steps(&self) -> i64 {
        self.get().steps()
    }

    /// Halve the total, refusing an odd one.
    #[napi(js_name = "halve")]
    pub fn halve(&mut self) -> napi::Result<i64> {
        self.get_mut().halve().map_err(err)
    }
}
impl Counter {
    fn get(&self) -> &hello::Counter {
        self.inner.as_ref().expect(EMPTIED)
    }
    fn get_mut(&mut self) -> &mut hello::Counter {
        self.inner.as_mut().expect(EMPTIED)
    }
}
