// @generated by jedem for the `node` target. Do not edit.
// Surface `hello` v0.1.0. Regenerate with `cargo jedem generate`.

// napi registers each function at module load, so there is no
// module function to write.
mod generated;
